const PLAYER_DATABASE = [
  { player: "Lionel Messi", clues: ["Ankara", "Katalan", "Solak"] },
  { player: "Cristiano Ronaldo", clues: ["Makine", "Atletizm", "Portekiz"] },
  { player: "Neymar", clues: ["Samba", "Şovmen", "Belgesel"] },
  { player: "Kylian Mbappe", clues: ["Sürat", "Horoz", "Maske"] },
  { player: "Erling Haaland", clues: ["Robot", "Kuzeyli", "Bitirici"] },
  { player: "Kevin De Bruyne", clues: ["Asist", "Vizyon", "Kızıl"] },
  { player: "Luka Modric", clues: ["Dış Ayak", "Hırvat", "Maestro"] },
  { player: "Toni Kroos", clues: ["Panzer", "Milimetrik", "Krampon"] },
  { player: "Rodri", clues: ["Çapa", "Sigorta", "Denge"] },
  { player: "Jude Bellingham", clues: ["Dinamizm", "Skorer", "Britanya"] },
  { player: "Vinicius Junior", clues: ["Dans", "Sürat", "Kanat"] },
  { player: "Lamine Yamal", clues: ["La Masia", "Ergen", "Yetenek"] },
  { player: "Pedri", clues: ["Zarafet", "Dar Alan", "Pasör"] },
  { player: "Robert Lewandowski", clues: ["Polonya", "Golcü", "Dokuz Numara"] },
  { player: "Antoine Griezmann", clues: ["Saç Boyası", "Bağlantı", "Maté"] },
  { player: "Jan Oblak", clues: ["Duvar", "Sloven", "Çizgi"] },
  {
    player: "Thibaut Courtois",
    clues: ["Geçit Vermez", "Uzun Boy", "Belçika"],
  },
  { player: "Alisson Becker", clues: ["Sakal", "Refleks", "Brezilya"] },
  {
    player: "Virgil van Dijk",
    clues: ["Mudahele", "Lider", "Hava Hakimiyeti"],
  },
  { player: "Mohamed Salah", clues: ["Firavun", "Kıvırcık", "Ters Ayak"] },
  { player: "Bukayo Saka", clues: ["İstikrar", "Londra", "Solak"] },
  { player: "Martin Odegaard", clues: ["Kaptan", "On Numara", "Kuzeyli"] },
  { player: "Bruno Fernandes", clues: ["Risk", "Penaltı", "Portekiz"] },
  { player: "Son Heung-min", clues: ["Asya", "İki Ayak", "Sürat"] },
  { player: "Harry Kane", clues: ["Lanet", "Bitirici", "Oyun Kurucu"] },
  { player: "Cole Palmer", clues: ["Soğuk", "Chelsea", "Solak"] },
  { player: "Declan Rice", clues: ["Çapa", "Pahalı", "İngiliz"] },
  { player: "Alexander Isak", clues: ["İsveç", "Zarif", "Uzun Boy"] },
  { player: "Trent Alexander-Arnold", clues: ["Bek", "Köşe Vuruşu", "Orta"] },
  { player: "Achraf Hakimi", clues: ["Fas", "Sprint", "Sağ Bek"] },
  { player: "Joao Neves", clues: ["Boyunluk", "Genç", "Tempo"] },
  { player: "Ousmane Dembele", clues: ["Öngörülemez", "Playstation", "Hız"] },
  { player: "Khvicha Kvaratskhelia", clues: ["Şampiyonluk", "Dribbling", "Kanat"] },
  { player: "Victor Osimhen", clues: ["Maske", "Forvet", "Sıçrama"] },
  { player: "Lautaro Martinez", clues: ["Boğa", "Inter", "Arjantin"] },
  { player: "Nicolo Barella", clues: ["Ciğersiz", "İtalyan", "Dinamizm"] },
  { player: "Rafael Leao", clues: ["Gülümseme", "Rap", "Sürat"] },
  { player: "Theo Hernandez", clues: ["Otoban", "Sol Bek", "Fransız"] },
  { player: "Mike Maignan", clues: ["Penaltı", "Siyahi", "Refleks"] },
  { player: "Federico Valverde", clues: ["Kavga", "Motor", "Uruguay"] },
  { player: "Eduardo Camavinga", clues: ["Her Mevki", "Örgü", "Fransız"] },
  { player: "Aurelien Tchouameni", clues: ["Piyano", "Ön Libero", "Fizik"] },
  { player: "Dani Carvajal", clues: ["Kupa Canavarı", "Mücadele", "Madrid"] },
  { player: "Antonio Rudiger", clues: ["Çılgın", "Tokat", "Maske"] },
  { player: "William Saliba", clues: ["Sakin", "Stoper", "Fransız"] },
  { player: "Gabriel Magalhaes", clues: ["Duran Top", "Sert", "Brezilya"] },
  { player: "Ruben Dias", clues: ["Komutan", "Savunma", "Portekiz"] },
  { player: "Bernardo Silva", clues: ["Minyatür", "Zeka", "Taktik"] },
  { player: "Phil Foden", clues: ["Saç Stili", "Solak", "İngiliz"] },
  { player: "Jamal Musiala", clues: ["Bambi", "Yılan", "Dribbling"] },
  { player: "Florian Wirtz", clues: ["Bayer", "Asist", "Vizyon"] },
  { player: "Joshua Kimmich", clues: ["Disiplin", "Joker", "Alman"] },
  { player: "Manuel Neuer", clues: ["Libero", "Dev", "Alman"] },
  { player: "Thomas Muller", clues: ["Boşluk", "Şakacı", "Zeka"] },
  { player: "Serge Gnabry", clues: ["Aşçı", "Kanat", "Alman"] },
  { player: "Leroy Sane", clues: ["Dövme", "Solak", "Sürat"] },
  { player: "Alphonso Davies", clues: ["Kanada", "Sürat", "Sol Bek"] },
  { player: "Dayot Upamecano", clues: ["Risk", "Fizik", "Fransız"] },
  { player: "Joao Felix", clues: ["Potansiyel", "Teknik", "Portekiz"] },
  { player: "Frenkie de Jong", clues: ["Ajax", "Taşıyıcı", "Orta Saha"] },
  { player: "Dani Olmo", clues: ["Saat", "Hatlar Arası", "İspanyol"] },
  { player: "Raphinha", clues: ["Pres", "Solak", "Barcelona"] },
  { player: "Ederson", clues: ["Pasör", "Dövme", "Brezilya"] },
  { player: "Gianluigi Donnarumma", clues: ["Euro 2020", "Dev", "İtalyan"] },
  { player: "Marquinhos", clues: ["Paris", "Kaptan", "Stoper"] },
  { player: "Vitinha", clues: ["Tempo", "Pasör", "Portekiz"] },
  { player: "Warren Zaire-Emery", clues: ["Lise", "Genç Kaptan", "Fransız"] },
  { player: "Paulo Dybala", clues: ["Maske", "Mücevher", "Solak"] },
  { player: "Romelu Lukaku", clues: ["Kalıplı", "Gövde", "Belçika"] },
  { player: "Ronaldinho", clues: ["Dişler", "Şov", "Gülümseme"] },
  { player: "Kaka", clues: ["Zarafet", "Milano", "İsa"] },
  { player: "Zinedine Zidane", clues: ["Kafa Atma", "Maestro", "Fransız"] },
  { player: "David Beckham", clues: ["Frikik", "Saç", "Magazin"] },
  { player: "Steven Gerrard", clues: ["Uzaktan Şut", "Kaptan", "Liverpool"] },
  { player: "Frank Lampard", clues: ["Skorer", "Chelsea", "Orta Saha"] },
  { player: "Didier Drogba", clues: ["Münih", "Fildişi", "Final"] },
  { player: "Thierry Henry", clues: ["Plase", "Arsenal", "Zarafet"] },
  { player: "Wayne Rooney", clues: ["Rövaşata", "Boks", "Savaşçı"] },
  { player: "Andrea Pirlo", clues: ["Şarap", "Regista", "Sakal"] },
  { player: "Clarence Seedorf", clues: ["Kas", "Hollanda", "Kupa"] },
  { player: "Sergio Ramos", clues: ["Son Dakika", "Kırmızı Kart", "Lider"] },
  { player: "Gerard Pique", clues: ["Shakira", "Başkan", "Katalan"] },
  { player: "Carles Puyol", clues: ["Kıvırcık", "Fedakar", "Kaptan"] },
  { player: "Marcelo", clues: ["Kıvırcık", "Teknik", "Sol Bek"] },
  { player: "Roberto Carlos", clues: ["Baldır", "Falso", "Füze"] },
  { player: "Iker Casillas", clues: ["Kaptan", "Real Madrid", "Efsane"] },
  { player: "Gianluigi Buffon", clues: ["Ömürlük", "Parma", "Efsane"] },
  { player: "Xavi", clues: ["Tiki-Taka", "Pusula", "Pas"] },
  { player: "Andres Iniesta", clues: ["Sihirbaz", "2010 Final", "Kontrol"] },
  { player: "Luis Suarez", clues: ["Isırma", "El", "Pistolero"] },
  { player: "Karim Benzema", clues: ["Sargı", "Fransız", "Altın Top"] },
  { player: "Zlatan Ibrahimovic", clues: ["Aslan", "Taekwondo", "Ego"] },
  { player: "Eden Hazard", clues: ["Burger", "Dribbling", "Chelsea"] },
  { player: "Arjen Robben", clues: ["İçe Kat", "Solak", "Kel"] },
  { player: "Franck Ribery", clues: ["Yara İzi", "Fransız", "Bayern"] },
  { player: "Sadio Mane", clues: ["Mütevazı", "Senegal", "Pres"] },
  { player: "Luis Figo", clues: ["Domuz Kafası", "Hain", "Portekiz"] },
  { player: "Rivaldo", clues: ["2002", "Solak", "Brezilya"] },
  { player: "Ronaldo Nazario", clues: ["Fenomen", "Saç Stili", "Diz"] },
  { player: "Ruud van Nistelrooy", clues: ["Kutu", "Bitirici", "Hollanda"] },
  { player: "Fernando Torres", clues: ["Çilli", "Maske", "Sürat"] },
  {
    player: "Fernando Muslera",
    clues: ["Nando", "Uruguay", "Yılların Kaptanı"],
  },
  { player: "Mauro Icardi", clues: ["Wanda", "Aşkın Olayım", "Tek Dokunuş"] },
  { player: "Lucas Torreira", clues: ["Atom Karınca", "Pres", "Uruguay"] },
  { player: "Dries Mertens", clues: ["Ciro", "Zeka", "Napoli"] },
  { player: "Baris Alper Yilmaz", clues: ["BAY", "Fizik", "Joker"] },
  { player: "Davinson Sanchez", clues: ["Duvar", "Agresif", "Kolombiya"] },
  { player: "Gabriel Sara", clues: ["Asist", "Solak", "Brezilya"] },
  { player: "Edin Dzeko", clues: ["Elmas", "Kule", "Kaptan"] },
  { player: "Dusan Tadic", clues: ["Balıkçı", "Lider", "Solak"] },
  { player: "Fred", clues: ["Enerji", "Pres", "Brezilya"] },
  { player: "Sofyan Amrabat", clues: ["Kel", "Savaşçı", "Fas"] },
  { player: "Youssef En-Nesyri", clues: ["Sıçrama", "Kule", "Fas"] },
  { player: "Dominik Livakovic", clues: ["Penaltı", "Sakin", "Hırvat"] },
  { player: "Sebastian Szymanski", clues: ["Pres", "Solak", "Uzak Şut"] },
  { player: "Bright Osayi-Samuel", clues: ["Boksör", "Sprint", "Sağ Bek"] },
  { player: "Rafa Silva", clues: ["Fırtına", "Portekiz", "Kontra"] },
  { player: "Gedson Fernandes", clues: ["Motor", "Dinamizm", "Sürüş"] },
  { player: "Mert Gunok", clues: ["Avusturya", "Refleks", "Milli"] },
  { player: "Milot Rashica", clues: ["Kosova", "Çalışkan", "Kanat"] },
  { player: "Arthur Masuaku", clues: ["Orta", "Sol Bek", "Kongo"] },
  { player: "Semih Kilicsoy", clues: ["Genç Boğa", "Bitirici", "Altyapı"] },
  { player: "Ugurcan Cakir", clues: ["Trabzon", "Kaptan", "Refleks"] },
  { player: "Anthony Nwakaeme", clues: ["Sihirbaz", "Top Saklama", "Ağır"] },
  { player: "Edin Visca", clues: ["İstikrar", "Asist", "Bosna"] },
  { player: "Batista Mendy", clues: ["Uzun Boy", "Ön Libero", "Fransız"] },
  { player: "Krzysztof Piatek", clues: ["Tabanca", "Polonya", "Golcü"] },
  { player: "Dimitris Pelkas", clues: ["Yunan", "Teknik", "Enerji"] },
  { player: "Tomas Ujfalusi", clues: ["Şef", "Saç Bandı", "Sert"] },
  { player: "Diego Lugano", clues: ["Tota", "Agresif", "Kafa"] },
  { player: "Sabri Sarioglu", clues: ["Reyiz", "55 Numara", "Hız"] },
  { player: "Selcuk Inan", clues: ["Xelçuk", "Frikik", "Kaptan"] },
  { player: "Emre Belozoglu", clues: ["Hırs", "Çatlak Ses", "Pasör"] },
  { player: "Burak Yilmaz", clues: ["Kral", "Ofsayt", "Lille"] },
  { player: "Volkan Demirel", clues: ["Kadıköy", "Agresif", "Ayı"] },
  { player: "Felipe Melo", clues: ["Pitbull", "Penaltı", "Sert"] },
  { player: "Johan Elmander", clues: ["Savaşçı", "Pres", "İsveç"] },
  { player: "Alex de Souza", clues: ["Heykel", "Kral", "On Numara"] },
  { player: "Wesley Sneijder", clues: ["Sniper", "Füze", "Hollanda"] },
  { player: "Dirk Kuyt", clues: ["Motor", "Joker", "Sarı Saç"] },
  { player: "Milan Baros", clues: ["Çek", "Sürat", "Forvet"] },
  { player: "Bafetimbi Gomis", clues: ["Aslan", "Örgü Saç", "Golcü"] },
  { player: "Moussa Sow", clues: ["Rövaşata", "Secde", "Senegal"] },
  { player: "Pierre Webo", clues: ["Kafa", "Kamerun", "Beyefendi"] },
  { player: "Marek Hamsik", clues: ["Mohikan", "Grande", "Slovak"] },
  { player: "Jose Sosa", clues: ["Maestro", "Arjantin", "Duran Top"] },
  { player: "Ricardo Quaresma", clues: ["Trivela", "Rabona", "Dövme"] },
  { player: "Mario Gomez", clues: ["Cha Cha", "Alman", "Tek Dokunuş"] },
  { player: "Pepe", clues: ["Kasap", "Sert", "Kel"] },
  { player: "Guti", clues: ["Topuk Pası", "Zarafet", "Madrid"] },
  { player: "Gheorghe Hagi", clues: ["Rumen", "Solak Deha", "On Numara"] },
  { player: "Arda Turan", clues: ["Lider", "Sol Kanat", "Yerli"] },
  { player: "Hasan Sas", clues: ["Kel", "Asabi", "Kanat"] },
  { player: "Tuncay Sanli", clues: ["Hırs", "Forvet", "Kadıköy"] },
  { player: "Pierre van Hooijdonk", clues: ["Frikik", "Kule", "Hollanda"] },
  { player: "Deivid de Souza", clues: ["Uzaktan Şut", "Brezilya", "Kanat"] },
  { player: "Nicolas Anelka", clues: ["Fransız", "Sürat", "Gezgin Forvet"] },
  { player: "Selcuk Sahin", clues: ["Ön Libero", "Yerli", "Uzaktan"] },
  { player: "Anderson Talisca", clues: ["Brezilya", "Solak", "Kule"] },
  { player: "Vincent Aboubakar", clues: ["Kamerun", "Hücumcu", "Çalım"] },
  { player: "Rachid Ghezzal", clues: ["Cezayir", "Asist", "Solak Kanat"] },
  { player: "Demba Ba", clues: ["Senegal", "Santrafor", "İnanç"] },
  { player: "Atiba Hutchinson", clues: ["İstikrar", "Çapa", "Kuzey Amerika"] },
  { player: "Nani", clues: ["Portekiz", "Kanat", "Takla"] },
  { player: "Robin van Persie", clues: ["Klas", "Hollanda", "Forvet"] },
  { player: "Samuel Eto'o", clues: ["Kamerun", "Efsane", "Bitirici"] },
  { player: "Claudio Taffarel", clues: ["Brezilya", "Kaleci", "Kupa"] },
  { player: "Gökhan Gönül", clues: ["Sağ Bek", "Mücadele", "Dinamik"] },
  { player: "Caner Erkin", clues: ["Solak", "Orta", "Asabi"] },
  { player: "Hami Mandirali", clues: ["Füze", "Yerli", "Duran Top"] },
  { player: "Ibrahima Yattara", clues: ["Çalım", "Afrika", "Kanat"] },
  { player: "Alexander Sörloth", clues: ["Kuzeyli", "Forvet", "Solak"] },
  {
    player: "Anastasios Bakasetas",
    clues: ["Yunan", "Solak Füze", "Orta Saha"],
  },
  { player: "Garry Rodrigues", clues: ["Hız", "Kanat", "Dribbling"] },
  { player: "Henry Onyekuru", clues: ["Sürat", "Nijerya", "Kanat Forvet"] },
  { player: "Ferdi Kadioglu", clues: ["Dribbling", "Joker", "Bek"] },
  { player: "Kerem Akturkoglu", clues: ["Sürat", "Kanat", "Yerli"] },
  { player: "Hakan Calhanoglu", clues: ["Milli", "Orta Saha", "Frikik"] },
  { player: "Arda Güler", clues: ["Genç Yetenek", "Solak", "Madrid"] },

  {
    player: "Michy Batshuayi",
    clues: ["Belçika", "Gezgin Forvet", "Son Dakika"],
  },
  { player: "Cenk Tosun", clues: ["Yerli", "Bitirici", "Paşa"] },
  { player: "Victor Nelsson", clues: ["Danimarka", "Sakin", "Stoper"] },
  {
    player: "Abdulkerim Bardakci",
    clues: ["Yerli", "Fizikli Stoper", "Solak"],
  },
  { player: "Irfan Can Kahveci", clues: ["Solak", "Plase", "Merkez"] },
  { player: "Enner Valencia", clues: ["Ekvador", "Skorer", "Forvet"] },
  { player: "Attila Szalai", clues: ["Macar", "Stoper", "Solak"] },
  { player: "Kim Min-jae", clues: ["Asya", "Duvar", "Stoper"] },
  { player: "Vedat Muriqi", clues: ["Kosova", "Kalıplı", "Santrafor"] },
  { player: "Ryan Babel", clues: ["Hollanda", "Gezgin", "Uzaktan Şut"] },
  { player: "Emirhan Topcu", clues: ["Yerli", "Geveze", "Stoper"] },
  { player: "Samet Akaydin", clues: ["Yerli", "Geri Pas", "Stoper"] },
  { player: "Salih Ucan", clues: ["Yerli", "Teknik", "Merkez"] },
  { player: "Dorukhan Tokoz", clues: ["Dinamizm", "Yerli", "Joker"] },
  { player: "Max Kruse", clues: ["Alman", "Zeka", "Forvet Arkası"] },
  { player: "Lukas Podolski", clues: ["Alman", "Solak Füze", "Forvet"] },
  { player: "Alper Potuk", clues: ["Ankara", "Yerli", "Merkez"] },
  { player: "Ozan Tufan", clues: ["Yerli", "Uzaktan Şut", "Dinamik"] },
  { player: "Volkan Sen", clues: ["Hız", "Çalım", "Asabi"] },
  { player: "Gökhan Töre", clues: ["Güçlü Kanat", "Yerli", "Çalım"] },
  { player: "Yasin Oztekin", clues: ["Kanat", "Yerli", "Skorer"] },
  { player: "Pablo Batalla", clues: ["Vefa", "On Numara", "Efsane"] },
  { player: "Mame Thiam", clues: ["Senegal", "Forvet", "Gezgin"] },
  { player: "Hugo Rodallega", clues: ["Kolombiya", "Forvet", "Gezgin"] },
  { player: "Theofanis Gekas", clues: ["Yunanistan", "Forvet", "Gezgin"] },
];

export function randomImposterPick(): { playerName: string; clue: string } {
  const pick =
    PLAYER_DATABASE[Math.floor(Math.random() * PLAYER_DATABASE.length)];
  const clue = pick.clues[Math.floor(Math.random() * pick.clues.length)];
  return { playerName: pick.player, clue };
}
