const PLAYER_DATABASE = [
  { player: "Lionel Messi", clues: ["Maestro", "Solak", "Dribbling"] },
  { player: "Cristiano Ronaldo", clues: ["Bitiricilik", "Lider", "Atletizm"] },
  { player: "Neymar", clues: ["Çalım", "Yaratıcılık", "Teknik"] },
  { player: "Kylian Mbappe", clues: ["Hız", "Patlayıcılık", "Bitirici"] },
  { player: "Erling Haaland", clues: ["Fizik", "Santrafor", "Güç"] },
  { player: "Kevin De Bruyne", clues: ["Pasör", "Vizyon", "Asist"] },
  { player: "Luka Modric", clues: ["Kontrol", "Tecrübe", "Maestro"] },
  { player: "Toni Kroos", clues: ["İsabet", "Tempo", "Pas"] },
  { player: "Rodri", clues: ["Denge", "Kontrol", "Altı Numara"] },
  { player: "Jude Bellingham", clues: ["Olgunluk", "Enerji", "Ceza Sahası"] },
  { player: "Vinicius Junior", clues: ["Çalım", "Hız", "Kanat"] },
  { player: "Lamine Yamal", clues: ["Yetenek", "Solak", "Gençlik"] },
  { player: "Pedri", clues: ["Zeka", "Pas", "Kontrol"] },
  { player: "Gavi", clues: ["Hırs", "Pres", "Enerji"] },
  { player: "Robert Lewandowski", clues: ["Golcü", "Bitiricilik", "Santrafor"] },
  { player: "Antoine Griezmann", clues: ["Çalışkanlık", "Akıl", "Bağlantı"] },
  { player: "Jan Oblak", clues: ["Refleks", "Kaleci", "Güven"] },
  { player: "Thibaut Courtois", clues: ["Uzunluk", "Kaleci", "Kurtarış"] },
  { player: "Alisson Becker", clues: ["Güven", "Kaleci", "Refleks"] },
  { player: "Virgil van Dijk", clues: ["Lider", "Savunma", "Hava Topu"] },
  { player: "Mohamed Salah", clues: ["Hız", "Solak", "Bitirici"] },
  { player: "Bukayo Saka", clues: ["Kanat", "Solak", "İstikrar"] },
  { player: "Martin Odegaard", clues: ["Vizyon", "Pas", "Oyun Kurucu"] },
  { player: "Bruno Fernandes", clues: ["Risk", "Pas", "Şut"] },
  { player: "Son Heung-min", clues: ["İki Ayak", "Hız", "Bitirici"] },
  { player: "Harry Kane", clues: ["Tamamlayıcı", "Pas", "Santrafor"] },
  { player: "Cole Palmer", clues: ["Soğukkanlılık", "Solak", "Yaratıcılık"] },
  { player: "Declan Rice", clues: ["İstikrar", "Güç", "Orta Saha"] },
  { player: "Alexander Isak", clues: ["Zarafet", "Santrafor", "Teknik"] },
  { player: "Trent Alexander-Arnold", clues: ["Orta", "Pas", "Oyun Kurma"] },
  { player: "Achraf Hakimi", clues: ["Sprint", "Bek", "Hız"] },
  { player: "Joao Neves", clues: ["Enerji", "Pres", "Orta Saha"] },
  { player: "Ousmane Dembele", clues: ["Dengesizlik", "İki Ayak", "Çalım"] },
  { player: "Khvicha Kvaratskhelia", clues: ["Yaratıcılık", "Çalım", "Kanat"] },
  { player: "Victor Osimhen", clues: ["Sıçrama", "Fizik", "Santrafor"] },
  { player: "Lautaro Martinez", clues: ["Mücadele", "Bitirici", "Santrafor"] },
  { player: "Nicolo Barella", clues: ["Dinamizm", "Pres", "Enerji"] },
  { player: "Rafael Leao", clues: ["Akıcılık", "Hız", "Kanat"] },
  { player: "Theo Hernandez", clues: ["Taşıma", "Bek", "Güç"] },
  { player: "Mike Maignan", clues: ["Kurtarış", "Kaleci", "Refleks"] },
  { player: "Federico Valverde", clues: ["Motor", "Enerji", "Şut"] },
  { player: "Eduardo Camavinga", clues: ["Esneklik", "Pres", "Teknik"] },
  { player: "Aurelien Tchouameni", clues: ["Güç", "Denge", "Orta Saha"] },
  { player: "Dani Carvajal", clues: ["Tecrübe", "Bek", "Mücadele"] },
  { player: "Antonio Rudiger", clues: ["Agresiflik", "Savunma", "Güç"] },
  { player: "William Saliba", clues: ["Sakinlik", "Savunma", "Pozisyon"] },
  { player: "Gabriel Magalhaes", clues: ["Sertlik", "Hava Topu", "Savunma"] },
  { player: "Ruben Dias", clues: ["Komutan", "Savunma", "Lider"] },
  { player: "Bernardo Silva", clues: ["Teknik", "Çeviklik", "Pas"] },
  { player: "Phil Foden", clues: ["Dokunuş", "Solak", "Yaratıcılık"] },
  { player: "Jamal Musiala", clues: ["Akışkanlık", "Dribbling", "Yaratıcılık"] },
  { player: "Florian Wirtz", clues: ["Sezgi", "Pas", "Yaratıcılık"] },
  { player: "Joshua Kimmich", clues: ["Disiplin", "Pas", "Lider"] },
  { player: "Manuel Neuer", clues: ["Süpürücü", "Kaleci", "Cesaret"] },
  { player: "Thomas Muller", clues: ["Pozisyon", "Akıl", "Boşluk"] },
  { player: "Serge Gnabry", clues: ["Bitiriş", "Kanat", "Şut"] },
  { player: "Leroy Sane", clues: ["Sürat", "Solak", "Kanat"] },
  { player: "Alphonso Davies", clues: ["Atletizm", "Hız", "Bek"] },
  { player: "Dayot Upamecano", clues: ["Kuvvet", "Savunma", "Fizik"] },
  { player: "Joao Felix", clues: ["Potansiyel", "Teknik", "Yaratıcılık"] },
  { player: "Frenkie de Jong", clues: ["Taşıyıcı", "Pas", "Kontrol"] },
  { player: "Dani Olmo", clues: ["Boşluk", "Teknik", "Pas"] },
  { player: "Raphinha", clues: ["Pres", "Solak", "Kanat"] },
  { player: "Ederson", clues: ["Dağıtım", "Kaleci", "Pas"] },
  { player: "Gianluigi Donnarumma", clues: ["Reaksiyon", "Kaleci", "Uzunluk"] },
  { player: "Marquinhos", clues: ["Kaptan", "Savunma", "Pozisyon"] },
  { player: "Vitinha", clues: ["Tempo", "Pas", "Kontrol"] },
  { player: "Warren Zaire-Emery", clues: ["Cesaret", "Enerji", "Orta Saha"] },
  { player: "Paulo Dybala", clues: ["Solak", "Teknik", "Zarafet"] },
  { player: "Romelu Lukaku", clues: ["Güç", "Santrafor", "Fizik"] },
  { player: "Ronaldinho", clues: ["Gülümseme", "Teknik", "Şov"] },
  { player: "Kaka", clues: ["Akıcılık", "Zarafet", "Hızlanma"] },
  { player: "Zinedine Zidane", clues: ["Zarafet", "Kontrol", "Maestro"] },
  { player: "David Beckham", clues: ["Orta", "Frikik", "İsabet"] },
  { player: "Steven Gerrard", clues: ["Şut", "Lider", "Motor"] },
  { player: "Frank Lampard", clues: ["Zamanlama", "Şut", "Ceza Sahası"] },
  { player: "Didier Drogba", clues: ["Final", "Güç", "Santrafor"] },
  { player: "Thierry Henry", clues: ["Akış", "Hız", "Bitirici"] },
  { player: "Wayne Rooney", clues: ["Mücadele", "Güç", "Şut"] },
  { player: "Andrea Pirlo", clues: ["Regista", "Pas", "Sakinlik"] },
  { player: "Clarence Seedorf", clues: ["Komple", "Güç", "Orta Saha"] },
  { player: "Sergio Ramos", clues: ["Agresiflik", "Lider", "Hava Topu"] },
  { player: "Gerard Pique", clues: ["Savunma", "Pas", "Pozisyon"] },
  { player: "Carles Puyol", clues: ["Mücadele", "Lider", "Cesaret"] },
  { player: "Marcelo", clues: ["Teknik", "Bek", "Çalım"] },
  { player: "Roberto Carlos", clues: ["Şut", "Bek", "Güç"] },
  { player: "Iker Casillas", clues: ["Refleks", "Kaleci", "Lider"] },
  { player: "Gianluigi Buffon", clues: ["Efsane", "Kaleci", "Lider"] },
  { player: "Xavi", clues: ["Tempo", "Pas", "Kontrol"] },
  { player: "Andres Iniesta", clues: ["Zarafet", "Kontrol", "Dribbling"] },
  { player: "Luis Suarez", clues: ["Bitirici", "Kurnazlık", "Santrafor"] },
  { player: "Karim Benzema", clues: ["Bağlantı", "Bitirici", "Teknik"] },
  { player: "Zlatan Ibrahimovic", clues: ["Ego", "Güç", "Akrobasi"] },
  { player: "Eden Hazard", clues: ["Çalım", "Alçak Merkez", "Yaratıcılık"] },
  { player: "Arjen Robben", clues: ["Solak", "İçe Kat", "Şut"] },
  { player: "Franck Ribery", clues: ["Çalım", "Kanat", "Teknik"] },
  { player: "Sadio Mane", clues: ["Hız", "Pres", "Bitirici"] },
  { player: "Luis Figo", clues: ["Kanat", "Teknik", "Orta"] },
  { player: "Rivaldo", clues: ["Solak", "Teknik", "Şut"] },
  { player: "Ronaldo Nazario", clues: ["Fenomen", "Patlayıcılık", "Bitirici"] },
  { player: "Ruud van Nistelrooy", clues: ["Ceza Sahası", "Bitirici", "Santrafor"] },
  { player: "Fernando Torres", clues: ["Hız", "Santrafor", "Bitirici"] },
  { player: "Fernando Muslera", clues: ["Refleks", "Kaptan", "Tecrübe"] },
  { player: "Mauro Icardi", clues: ["Bitiricilik", "Ceza Sahası", "Golcülük"] },
  { player: "Lucas Torreira", clues: ["Pres", "Mücadele", "Enerji"] },
  { player: "Dries Mertens", clues: ["Yaratıcılık", "Teknik", "Zeka"] },
  { player: "Baris Alper Yilmaz", clues: ["Atletizm", "Çok Yönlülük", "Hız"] },
  { player: "Davinson Sanchez", clues: ["Savunma", "Güç", "Hava Topu"] },
  { player: "Gabriel Sara", clues: ["Pas", "Tempo", "Teknik"] },
  { player: "Edin Dzeko", clues: ["Bitiricilik", "Tecrübe", "Santrafor"] },
  { player: "Dusan Tadic", clues: ["Vizyon", "Pas", "Lider"] },
  { player: "Fred", clues: ["Enerji", "Pres", "Orta Saha"] },
  { player: "Sofyan Amrabat", clues: ["Güç", "Savunma", "Mücadele"] },
  { player: "Youssef En-Nesyri", clues: ["Hava Topu", "Santrafor", "Bitirici"] },
  { player: "Dominik Livakovic", clues: ["Refleks", "Kaleci", "Sakinlik"] },
  { player: "Sebastian Szymanski", clues: ["Yaratıcılık", "Tempo", "Pas"] },
  { player: "Bright Osayi-Samuel", clues: ["Sprint", "Bek", "Hız"] },
  { player: "Rafa Silva", clues: ["Teknik", "Yaratıcılık", "Hareketlilik"] },
  { player: "Gedson Fernandes", clues: ["Dinamizm", "Enerji", "Taşıma"] },
  { player: "Mert Gunok", clues: ["Refleks", "Kaleci", "Tecrübe"] },
  { player: "Milot Rashica", clues: ["Kanat", "Hız", "Çalım"] },
  { player: "Arthur Masuaku", clues: ["Orta", "Bek", "Teknik"] },
  { player: "Semih Kilicsoy", clues: ["Potansiyel", "Bitiricilik", "Gençlik"] },
  { player: "Ugurcan Cakir", clues: ["Refleks", "Kaleci", "Lider"] },
  { player: "Anthony Nwakaeme", clues: ["Güç", "Çalım", "Kanat"] },
  { player: "Edin Visca", clues: ["Asist", "Kanat", "Tecrübe"] },
  { player: "Batista Mendy", clues: ["Fizik", "Mücadele", "Orta Saha"] },
  { player: "Krzysztof Piatek", clues: ["Bitiricilik", "Santrafor", "Ceza Sahası"] },
  { player: "Dimitris Pelkas", clues: ["Teknik", "Yaratıcılık", "Solak"] },
  { player: "Tomas Ujfalusi", clues: ["Savunma", "Sertlik", "Kaptan"] },
  { player: "Diego Lugano", clues: ["Lider", "Kafa", "Savunma"] },
  { player: "Sabri Sarioglu", clues: ["Mücadele", "Enerji", "Bek"] },
  { player: "Selcuk Inan", clues: ["Frikik", "Pas", "Oyun Kurucu"] },
  { player: "Emre Belozoglu", clues: ["Hırs", "Pas", "Lider"] },
  { player: "Burak Yilmaz", clues: ["Koşu", "Bitiricilik", "Santrafor"] },
  { player: "Volkan Demirel", clues: ["Kaleci", "Lider", "Agresiflik"] },
  { player: "Felipe Melo", clues: ["Sertlik", "Tutku", "Mücadele"] },
  { player: "Johan Elmander", clues: ["Çalışkanlık", "Pres", "Forvet"] },
  { player: "Alex de Souza", clues: ["Vizyon", "Frikik", "10 Numara"] },
  { player: "Wesley Sneijder", clues: ["Şut", "Pas", "Beyin"] },
  { player: "Dirk Kuyt", clues: ["Çalışkanlık", "Pres", "Mücadele"] },
  { player: "Milan Baros", clues: ["Hız", "Santrafor", "Koşu"] },
  { player: "Elano", clues: ["Teknik", "Frikik", "Pas"] },
  { player: "Bafetimbi Gomis", clues: ["Aslan", "Bitirici", "Güç"] },
  { player: "Moussa Sow", clues: ["Akrobasi", "Bitiricilik", "Santrafor"] },
  { player: "Pierre Webo", clues: ["Kafa", "Güç", "Golcü"] },
  { player: "Marek Hamsik", clues: ["Mohikan", "Pas", "Lider"] },
  { player: "Jose Sosa", clues: ["Teknik", "Vizyon", "Pas"] },
  { player: "Ricardo Quaresma", clues: ["Trivela", "Yetenek", "Kanat"] },
  { player: "Mario Gomez", clues: ["Ceza Sahası", "Bitirici", "Santrafor"] },
  { player: "Pepe", clues: ["Sertlik", "Savunma", "Agresiflik"] },
  { player: "Guti", clues: ["Topuk Pası", "Vizyon", "Teknik"] },
];

export function randomImposterPick(): { playerName: string; clue: string } {
  const pick = PLAYER_DATABASE[Math.floor(Math.random() * PLAYER_DATABASE.length)];
  const clue = pick.clues[Math.floor(Math.random() * pick.clues.length)];
  return { playerName: pick.player, clue };
}
