export const TARGET_SCORES = [5, 10, 15] as const;

// export const INITIAL_SEEDS = [
//   "JR",
//   "CR",
//   "LM",
//   "MB",
//   "KD",
//   "RN",
//   "VK",
//   "AM",
//   "DS",
//   "FG",
//   "TS",
//   "MH",
//   "GP",
//   "EF",
//   "BA",
//   "NL",
//   "MS",
//   "PL",
//   "SA",
//   "JO",
// ];

export const INITIAL_SEEDS = [
  "JR",
  "CR",
  "LM",
  "MB",
  "KD",
  "RN",
  "AM",
  "DS",
  "TS",
  "BA",
  "SA",
  "RM",
  "AC",
  "RA",
  "MC",
  "LS",
  "MG",
  "RS",
  "SC",
  "DC",
  "DM",
  "RD",
  "SG",
  "TM",
  "TC",
  "JD",
  "JC",
  "KR",
  "LA",
  "NG",
  "PA",
  "PG",
  "TR",
  "CA",
  "DR",
  "FA",
  "FR",
  "GA",
  "GR",
  "JA",
  "JM",
  "KA",
  "KC",
  "LC",
  "LR",
  "NA",
  "NC",
  "PC",
  "PD",
  "PR",
  "RG",
  "RR",
  "SP",
  "TA",
  "EE",
  "MM",
  "CC",
  "GG",
  "JJ",
  "BB",
];
export const TEAM_DATABASE = [
  { league: "Premier League", name: "Manchester United" },
  { league: "Premier League", name: "Liverpool" },
  { league: "Premier League", name: "Arsenal" },
  { league: "Premier League", name: "Manchester City" },
  { league: "Premier League", name: "Chelsea" },
  { league: "Premier League", name: "Tottenham" },
  { league: "Premier League", name: "Newcastle" },
  { league: "Premier League", name: "Aston Villa" },
  { league: "La Liga", name: "Real Madrid" },
  { league: "La Liga", name: "Barcelona" },
  { league: "La Liga", name: "Atletico Madrid" },
  { league: "La Liga", name: "Valencia" },
  { league: "La Liga", name: "Sevilla" },
  { league: "Germany", name: "Bayern Munich" },
  { league: "Germany", name: "Borussia Dortmund" },
  { league: "Germany", name: "Bayer Leverkusen" },
  { league: "France", name: "PSG" },
  { league: "France", name: "Marseille" },
  { league: "France", name: "Lyon" },
  { league: "France", name: "Monaco" },
  { league: "Italy", name: "Juventus" },
  { league: "Italy", name: "AC Milan" },
  { league: "Italy", name: "Inter Milan" },
  { league: "Italy", name: "Roma" },
  { league: "Italy", name: "Napoli" },
  { league: "Italy", name: "Lazio" },
  { league: "Turkey", name: "Galatasaray" },
  { league: "Turkey", name: "Fenerbahce" },
  { league: "Turkey", name: "Besiktas" },
  { league: "Turkey", name: "Trabzonspor" },
  { league: "Turkey", name: "Basaksehir" },
  { league: "Netherlands", name: "Ajax" },
  { league: "Netherlands", name: "PSV" },
  { league: "Portugal", name: "Benfica" },
  { league: "Portugal", name: "Porto" },
  { league: "Portugal", name: "Sporting" },
] as const;
