export const TARGET_SCORES = [5, 10, 15] as const;

// export const INITIAL_SEEDS = [
//   "JR",
//   "CR",
//   "LM",
//   "MB",
//   "KD",
//   "RN",
//   "VK",
//   "AM",
//   "DS",
//   "FG",
//   "TS",
//   "MH",
//   "GP",
//   "EF",
//   "BA",
//   "NL",
//   "MS",
//   "PL",
//   "SA",
//   "JO",
// ];

export const INITIAL_SEEDS = [
  "JR",
  "CR",
  "LM",
  "MB",
  "KD",
  "RN",
  "AM",
  "DS",
  "TS",
  "BA",
  "SA",
  "RM",
  "AC",
  "RA",
  "MC",
  "LS",
  "MG",
  "RS",
  "SC",
  "DC",
  "DM",
  "RD",
  "SG",
  "TM",
  "TC",
  "JD",
  "JC",
  "KR",
  "LA",
  "NG",
  "PA",
  "PG",
  "TR",
  "CA",
  "DR",
  "FA",
  "FR",
  "GA",
  "GR",
  "JA",
  "JM",
  "KA",
  "KC",
  "LC",
  "LR",
  "NA",
  "NC",
  "PC",
  "PD",
  "PR",
  "RG",
  "RR",
  "SP",
  "TA",
  "EE",
  "MM",
  "CC",
  "GG",
  "JJ",
  "BB",
];
export const TEAM_DATABASE = [
  { league: "Premier League", name: "Manchester United" },
  { league: "Premier League", name: "Liverpool" },
  { league: "Premier League", name: "Arsenal" },
  { league: "Premier League", name: "Manchester City" },
  { league: "Premier League", name: "Chelsea" },
  { league: "Premier League", name: "Tottenham" },
  { league: "Premier League", name: "Newcastle" },
  { league: "Premier League", name: "Aston Villa" },
  { league: "Premier League", name: "Brighton Albion" },
  { league: "Premier League", name: "Westham United" },
  { league: "La Liga", name: "Real Madrid" },
  { league: "La Liga", name: "Barcelona" },
  { league: "La Liga", name: "Atletico Madrid" },
  { league: "La Liga", name: "Valencia" },
  { league: "La Liga", name: "Sevilla" },
  { league: "Germany", name: "Bayern Munich" },
  { league: "Germany", name: "Borussia Dortmund" },
  { league: "Germany", name: "Bayer Leverkusen" },
  { league: "Germany", name: "Leipzig" },
  { league: "Germany", name: "Schalke" },
  { league: "France", name: "PSG" },
  { league: "France", name: "Marseille" },
  { league: "France", name: "Lyon" },
  { league: "France", name: "Monaco" },
  { league: "France", name: "Lille" },
  { league: "Italy", name: "Juventus" },
  { league: "Italy", name: "AC Milan" },
  { league: "Italy", name: "Inter Milan" },
  { league: "Italy", name: "Roma" },
  { league: "Italy", name: "Napoli" },
  { league: "Italy", name: "Lazio" },
  { league: "Turkey", name: "Galatasaray" },
  { league: "Turkey", name: "Fenerbahce" },
  { league: "Turkey", name: "Besiktas" },
  { league: "Turkey", name: "Trabzonspor" },
  { league: "Turkey", name: "Antalya" },
  { league: "Turkey", name: "Bursa" },
  { league: "Netherlands", name: "Ajax" },
  { league: "Netherlands", name: "PSV" },
  { league: "Portugal", name: "Benfica" },
  { league: "Portugal", name: "Porto" },
  { league: "Portugal", name: "Sporting" },
] as const;

export const TEAM_LOGOS: Record<string, string> = {
  "Manchester United": "/manu.png",
  Liverpool: "/liverpool.png",
  Arsenal: "/arsenal.png",
  "Manchester City": "/mancity.png",
  Chelsea: "/chelsea.png",
  Tottenham: "/tottenham.png",
  Newcastle: "/newcastle.png",
  "Aston Villa": "/aston.png",
  "Real Madrid": "/real-madrid.png",
  Barcelona: "/barcelona.png",
  "Atletico Madrid": "/atletico.png",
  Sevilla: "/sevilla.png",
  "Bayern Munich": "/bayern.png",
  "Borussia Dortmund": "/dortmund.png",
  "Bayer Leverkusen": "/leverkusen.png",
  PSG: "/psg.png",
  Marseille: "/marseille.png",
  Lyon: "/lyon.png",
  Monaco: "/monaco.svg",
  Juventus: "/juventus.png",
  "AC Milan": "/milan.png",
  "Inter Milan": "/inter.png",
  Roma: "/roma.png",
  Napoli: "/napoli.svg",
  Galatasaray: "/galatasaray.png",
  Fenerbahce: "/fenerbahce.png",
  Besiktas: "/besiktas.svg",
  Trabzonspor: "/trabzon.png",
  Basaksehir: "/basaksehir.png",
  Ajax: "/ajax.png",
  PSV: "/psv.png",
  Benfica: "/benfica.png",
  Porto: "/porto.png",
  Sporting: "/sporting.png",
  Lazio: "/lazio.png",
  "Brighton Albion": "/brighton.png",
  "Westham United": "/westham.png",
  Leipzig: "/leipzig.png",
  Schalke: "/schalke.png",
  Lille: "/lille.png",
  Antalya: "/antalya.png",
  Bursa: "/bursa.png",
  Valencia: "/valencia.png",
};


